// The QUANtum Deal Review question bank (DealReview-Questions.docx), as data.
//
// One source for the tab, the AI fill and the Word export, so the three can't
// drift into asking different questions. The client fetches this from the
// server rather than keeping its own copy.
//
// Keys are stored against every answer, so they are positional but must stay
// stable: APPEND new questions to the end of a section's `deeper` list, never
// insert or reorder, or existing answers silently move to the wrong question.
// Rewording a question in place is fine.
//
// Per-question flags:
//   applies  -- only relevant to some deals ('existing', 'ot', 'gov',
//               'hardware', 'pov'). Shown as a hint; the answer may be N/A.
//   manual   -- nothing in notes or transcripts can answer it (it lives in
//               another system), so the AI pass leaves it alone.
//   computed -- filled from the app's own data rather than from text.
//   customerVoice -- only the customer saying it counts ("in their words",
//               "unprompted", "did the customer validate"). The evidence-based
//               fill won't mark these answered without a customer speaker.
//
// Section flags:
//   killer   -- inverted polarity: each item is a red flag that is either
//               present or clear, not a question that is answered or not.

const RAW = [
  {
    key: 'current_state', title: 'Current State', headlineCustomerVoice: true,
    headline: 'What is the customer’s current state, in their words?',
    deeper: [
      { q: 'Can the champion repeat the problem back in their own words, unprompted — not just nod along to our framing of it?', customerVoice: true },
      { q: 'Have we validated that problem statement with a second person (a coach, a technical stakeholder, or the economic buyer), or does it only exist in the champion’s telling?' },
      { q: 'Is the problem expressed in both a technical deficiency and an impact to the business, e.g. a file-based threat and removable-media control problem for OT/ICS engineering, a data exfiltration or compliance problem for a CISO, an uptime and safety problem for a plant manager? The same deal often needs three different correct framings, not one generic pitch.' },
      { q: 'Does the problem statement connect cleanly to an OPSWAT capability, e.g. CDR for file-based threats, DLP for data loss, Kiosk or the Unidirectional/Bilateral Security Gateway for physical and air-gapped control, or is the team stretching the platform to fit a problem it doesn’t map to well?' },
      { q: 'What does the customer do today for this problem (e.g. nothing, a manual process, an incumbent tool) and what specifically is failing about it?' },
      { q: 'What changed recently to make this urgent — an incident, an audit, a regulatory deadline, new leadership, an M&A event?' },
      { q: 'Have we asked the harder follow-up questions (“what have you tried before and why didn’t it work,” “who else has looked at this and passed”) rather than stopping at the first comfortable answer?' }
    ]
  },
  {
    key: 'desired_state', title: 'Desired State', headlineCustomerVoice: true,
    headline: 'What do they want to achieve, in their words?',
    deeper: [
      { q: 'What does the customer believe “good” looks like, in their own terms, and have we captured that in writing?', customerVoice: true },
      { q: 'Has the customer articulated the gap between current and desired state themselves, or is that gap our assumption?', customerVoice: true }
    ]
  },
  {
    key: 'negative_consequences', title: 'Negative Consequences',
    headline: 'What are the consequences of doing nothing?',
    deeper: [
      { q: 'Is there a hard external deadline — an audit date, a compliance deadline, a cyber insurance renewal, a contract expiration — or is the urgency self-generated by OPSWAT’s end of quarter?' },
      { q: 'Is there a hard internal deadline — a board-imposed functional capabilities requirement, an adjacent project underpinned by this?' },
      { q: 'Has the customer stated the consequence of inaction in their own words (regulatory exposure, downtime, breach cost, audit failure), or have we only asserted it on their behalf?', customerVoice: true },
      { q: 'If OT/ICS is involved: is the negative consequence framed in terms of safety and reliability (the language that actually moves OT budget), not just generic cybersecurity risk language?', applies: 'ot' },
      { q: 'Does the negative consequence attach to a specific person’s responsibility (the CISO who owns the audit finding, the plant manager who owns uptime), or is it diffuse and ownerless?' }
    ]
  },
  {
    key: 'positive_outcomes', title: 'Positive Business Outcomes',
    headline: 'What is the business benefit?',
    deeper: [
      { q: 'Has the business impact been quantified — P-R-E-T-Q-K (Profit, Revenue, Expense, Time-to-market, Quality, risK) — cyber-resilience readiness, hours of manual labor eliminated, tools consolidated, downtime hours avoided, audit fine and/or remediation cost avoided, insurance premium impact – quantitative claims vs. qualitative claims.' },
      { q: 'Did the customer supply or validate these numbers, or are they entirely OPSWAT’s estimate? Numbers the customer helped build are numbers they’ll defend internally; numbers we handed them often aren’t.', customerVoice: true },
      { q: 'Does the economic buyer track these particular metrics already or have we picked metrics that matter to us but not to them?' },
      { q: 'For renewals/expansions: can we claim Past Value Delivered (PVD) — quantitative benefits the customer actually realized since initial deployment (scans performed, incidents caught, audit findings closed), or is the value story still hypothetical months into the relationship?', applies: 'existing' }
    ]
  },
  {
    key: 'required_capabilities', title: 'Required Capabilities',
    headline: 'What capabilities must be proven for customer acceptance of the solution?',
    deeper: [
      { q: 'What technical criteria must our solution meet and how does that criteria connect to the business drivers? E.g. faster and more thorough scans of contractor laptops speed time-to-market by allowing the customer to take advantage of new innovations for the manufacturing floor faster and with greater confidence.' },
      { q: 'For hardware components (Kiosk, Netwall, etc.): has procurement accounted for a separate hardware purchase order and lead time, distinct from software/subscription terms?', applies: 'hardware' },
      { q: 'Is there a change advisory board, plant safety/change-control window, or OT network segmentation review that must approve any new device before it touches the OT network?', applies: 'ot' },
      { q: 'For government/public sector deals: is an Authority to Operate (ATO), FedRAMP status, or equivalent authorization required, and where does that sit in the process?', applies: 'gov' },
      { q: 'What is required for technical validation (i.e. demo, workshop, POV, all the above)' },
      { q: 'Have demos been done? How many times and what stakeholders?' }
    ]
  },
  {
    key: 'technical_metrics', title: 'Technical Metrics',
    headline: 'Is OPSWAT a technical fit?',
    deeper: [
      { q: 'Has a workshop been done?' },
      { q: 'If a POV is/was needed, is there a success plan that was agreed to by the customer?', applies: 'pov' },
      { q: 'Does the success plan contain the required use cases and test cases? Does it align to the business drivers? Has the technical buyer agreed with the success plan?', applies: 'pov' },
      { q: 'Is there a partner SE that co-owns the POV plan and success criteria?', applies: 'pov' },
      { q: 'Are there required integrations?' },
      { q: 'Has the partner validated the architecture and integration fit?' },
      { q: 'Who can kill this on technical grounds, and are they satisfied?' },
      { q: 'Is hardware sizing confirmed, and lead time built into the customer’s own project timeline?', applies: 'hardware' },
      { q: 'Is software sizing confirmed?' },
      { q: 'What is the status of the POV, and if not complete, is there sufficient time in the quarter to complete it?', applies: 'pov' }
    ]
  },
  {
    key: 'how_we_do_it', title: 'How We Do It',
    headline: 'What are the unique elements of our proposal?',
    deeper: [
      { q: 'What are the elements of the OPSWAT solution that solve the customer’s problems and delivers the desired outcomes? (technology, services, timing, etc.)' },
      { q: 'How will these be prioritized in the proposal?' }
    ]
  },
  {
    key: 'why_better', title: 'Why We Are Better',
    headline: 'How are we differentiated?',
    deeper: [
      { q: 'Can the team state OPSWAT’s differentiation for this specific deal — breadth and depth of multiscanning, Deep CDR™ Technology, purpose-built OT/critical infrastructure hardware (MetaDefender Kiosk, the Unidirectional and Bilateral Security Gateways), or more than twenty years protecting critical infrastructure — rather than a generic “we’re the best” claim?' },
      { q: 'Have we shaped the customer’s decision criteria to reflect what OPSWAT does uniquely well, or are we responding to criteria written around a competitor’s strengths or a generic checklist?' },
      { q: 'What is the named competitive alternative, and do we know specifically where we’re stronger and where we’re weaker against it for this account’s use case?' },
      { q: 'Has the champion told us, unprompted, why they prefer OPSWAT — or are we assuming preference because the deal is still open?', customerVoice: true },
      { q: 'Where is the team currently winning on relationship or price rather than differentiated value? That’s a flag, not a strength — it rarely survives procurement scrutiny or a renewal cycle.' },
      { q: 'Are we differentiated and will the customer agree that we’re the best technical fit?' }
    ]
  },
  {
    key: 'proof_points', title: 'Proof Points',
    headline: 'What evidence exists to bolster our claims?',
    deeper: [
      { q: 'Have we offered a reference or case study relevant to this customer’s vertical — critical infrastructure, government, industrial, or enterprise IT — rather than a generic reference list?' },
      { q: 'Has the customer actually engaged with that proof (reference call completed, case study read and discussed), or was it just sent and forgotten?' },
      { q: 'Does the proof point map to the specific differentiator we’re selling on (OT-specific hardware, Deep CDR breadth, prevention-first approach), or is it a mismatched, generic success story?' },
      { q: 'For a live POV, are the results being tracked as a proof point we can cite going forward, or will they be lost once the deal closes?', applies: 'pov' }
    ]
  },
  {
    key: 'process_alignment', title: 'Process & Alignment',
    headline: 'Do we have a close plan?',
    deeper: [
      { q: 'Who wrote the decision criteria, and when — before or after OPSWAT was engaged? Criteria written before engagement often favor an incumbent or a generic checklist.' },
      { q: 'Have we personally met the economic buyer, or are we relying entirely on the champion to carry the message upward?' },
      { q: 'Is a partner exec engaged with the customer’s economic buyer?' },
      { q: 'Is a partner sponsor mapped 1:1 against our OPSWAT sponsor?' },
      { q: 'Is there a coach — someone inside the account, possibly not the champion, who helps us understand internal politics and validates our read of the deal?' },
      { q: 'Is IT security, OT/ICS engineering, or physical security/facilities the actual driver here, and have we built relationships across all three where relevant, since budget and priority often sit in different places?' },
      { q: 'Are we multi-threaded across IT, OT, procurement/legal, and physical security, or is this deal one relationship away from stalling?' },
      { q: 'Can the partner reach stakeholders beyond the primary contact (security, ops, procurement)?' },
      { q: 'Does our partner share competitive intel and displacement angles?' },
      { q: 'Who loses politically if this deal happens — an incumbent vendor’s internal champion, an OT team resistant to IT tools on their network — and have we addressed that person directly rather than working around them?' },
      { q: '(Existing accounts) Is the original executive sponsor from the initial deal still in their role?', applies: 'existing' },
      { q: 'Where are we in the customer’s risk assessment cycle at this account — SOC 2/ISO reports requested, architecture review, AI model risk office, security questionnaire?' },
      { q: 'Is deal registration locked with the distributor?' },
      { q: 'Is pricing, quoting, and discount terms confirmed with the partner?' },
      { q: 'Does a close plan exist that has all the steps necessary to close this deal?' }
    ]
  },
  {
    key: 'deal_killers', title: 'Deal Killer Checklist', killer: true,
    headline: 'What could kill this deal?',
    deeper: [
      { q: 'Champion cannot restate the problem or the value in their own words' },
      { q: 'No metrics that matter have been quantified, or the only numbers on the table are OPSWAT’s unvalidated estimates' },
      { q: 'Decision criteria were set before OPSWAT was engaged and haven’t been reshaped' },
      { q: 'No differentiated reason to buy beyond price or relationship' },
      { q: 'Single-threaded with no access to the economic buyer' },
      { q: 'No documented mutual action plan or scheduled next step' },
      { q: 'OPSWAT vendor risk review not yet started for a deal expected to close this period' },
      { q: 'Deal has slipped more than once already' },
      { q: 'Compelling event is soft or self-imposed by OPSWAT, not the customer' },
      { q: 'Hardware lead time or site installation logistics haven’t been factored into the customer’s own timeline', applies: 'hardware' },
      { q: 'OT change-control or network segmentation approval hasn’t been scheduled for a deal touching the OT network', applies: 'ot' },
      { q: '(Existing accounts) Original champion or sponsor has left with no replacement relationship', applies: 'existing' },
      { q: '(Existing accounts) An open, unresolved critical support escalation exists at the account', applies: 'existing' }
    ]
  },
  {
    key: 'account_health', title: 'Account & Product Health',
    headline: 'Will the customer do another deal with us?', applies: 'existing',
    deeper: [
      { q: 'Has the customer fully adopted and/or consumed their current products?' },
      { q: 'Had they implemented with the help of Professional Services?' },
      { q: 'Is a TAM assigned, and if so, what is the cadence of engagement?', manual: true },
      { q: 'What is the customer’s support case volume and trend — silence isn’t automatically good.', manual: true },
      { q: 'Is the original sponsor still in role?' },
      { q: 'When was the last executive business review? Is there executive alignment or only champion alignment?' },
      { q: 'Does the customer have a history of closing on time?', manual: true },
      { q: 'Does the customer have a history of paying on time?', manual: true },
      { q: 'What is the customer’s willingness to be a reference?' }
    ]
  },
  {
    key: 'forecast', title: 'Forecast Calibration',
    headline: 'What does forecast history tell us?', manual: true,
    deeper: [
      { q: 'What is the age of this deal?', computed: 'age' },
      { q: 'How long has it been in the current stage?', computed: 'days_in_stage' },
      { q: 'How many times has this deal slipped a quarter, and why?', computed: 'slips' },
      { q: 'What is the AE’s historical forecast accuracy at this stage/confidence level?', manual: true }
    ]
  }
];

const APPLIES_LABEL = {
  existing: 'Existing accounts',
  ot: 'OT/ICS',
  gov: 'Government',
  hardware: 'Hardware',
  pov: 'POV'
};

// Flatten into { section, key, text, ... } with stable keys: `<section>.h` for
// the headline and `<section>.<n>` for the n-th deeper question (1-based).
const SECTIONS = RAW.map((s, i) => ({
  key: s.key,
  number: i + 1,
  title: s.title,
  killer: !!s.killer,
  applies: s.applies || null,
  questions: [
    { key: `${s.key}.h`, text: s.headline, headline: true, manual: !!s.manual, applies: s.applies || null,
      customerVoice: !!s.headlineCustomerVoice },
    ...s.deeper.map((d, n) => ({
      key: `${s.key}.${n + 1}`,
      text: d.q,
      headline: false,
      manual: !!d.manual,
      computed: d.computed || null,
      applies: d.applies || s.applies || null,
      customerVoice: !!d.customerVoice
    }))
  ]
}));

const QUESTIONS = SECTIONS.flatMap(s => s.questions.map(q => ({ ...q, section: s.key, killer: s.killer })));
const BY_KEY = new Map(QUESTIONS.map(q => [q.key, q]));

// Answered/partial/unanswered/na for ordinary questions; flagged/clear for
// the deal-killer items, where "flagged" means the risk is present.
const STATUSES = ['answered', 'partial', 'unanswered', 'na', 'flagged', 'clear'];
// Whose words the answer rests on. 'team' is the AE/SE's own read, e.g. from
// an internal call; it never counts as the customer having said it.
// 'app' = taken from the notebook's own records (contacts, next steps, history).
const VOICES = ['customer', 'team', 'inferred', 'app'];

module.exports = { SECTIONS, QUESTIONS, BY_KEY, STATUSES, VOICES, APPLIES_LABEL };
